#!/usr/bin/env python

Import('env')
Import('env_modules')

env_polyvector = env_modules.Clone()

# Godot's own source files
env_polyvector.add_source_files(env.modules_sources, "*.cpp")

if ARGUMENTS.get('platform') == "windows":
	env_polyvector.Append(CXXFLAGS = ['/EHsc'])
if ARGUMENTS.get('platform') == "android":
	env_polyvector.Append(CXXFLAGS = ['-std=c++14'])
